// Code generated by protoc-gen-go. DO NOT EDIT.
// source: serve.proto

/*
Package serve is a generated protocol buffer package.

It is generated from these files:
	serve.proto

It has these top-level messages:
	GetFileRequest
	GetFileResponse
	GetAnnotationsRequest
	GetAnnotationsResponse
	GetFilesRequest
	GetFilesResponse
	GetPackagesRequest
	GetPackagesResponse
*/
package serve

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import goref_proto "github.com/korfuri/goref/proto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetFileRequest struct {
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
}

func (m *GetFileRequest) Reset()                    { *m = GetFileRequest{} }
func (m *GetFileRequest) String() string            { return proto.CompactTextString(m) }
func (*GetFileRequest) ProtoMessage()               {}
func (*GetFileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetFileRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type GetFileResponse struct {
	Path     string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Contents string `protobuf:"bytes,2,opt,name=contents" json:"contents,omitempty"`
}

func (m *GetFileResponse) Reset()                    { *m = GetFileResponse{} }
func (m *GetFileResponse) String() string            { return proto.CompactTextString(m) }
func (*GetFileResponse) ProtoMessage()               {}
func (*GetFileResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetFileResponse) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *GetFileResponse) GetContents() string {
	if m != nil {
		return m.Contents
	}
	return ""
}

type GetAnnotationsRequest struct {
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
}

func (m *GetAnnotationsRequest) Reset()                    { *m = GetAnnotationsRequest{} }
func (m *GetAnnotationsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAnnotationsRequest) ProtoMessage()               {}
func (*GetAnnotationsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetAnnotationsRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type GetAnnotationsResponse struct {
	Path       string             `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Annotation []*goref_proto.Ref `protobuf:"bytes,2,rep,name=annotation" json:"annotation,omitempty"`
}

func (m *GetAnnotationsResponse) Reset()                    { *m = GetAnnotationsResponse{} }
func (m *GetAnnotationsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAnnotationsResponse) ProtoMessage()               {}
func (*GetAnnotationsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetAnnotationsResponse) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *GetAnnotationsResponse) GetAnnotation() []*goref_proto.Ref {
	if m != nil {
		return m.Annotation
	}
	return nil
}

type GetFilesRequest struct {
	Package string `protobuf:"bytes,1,opt,name=package" json:"package,omitempty"`
}

func (m *GetFilesRequest) Reset()                    { *m = GetFilesRequest{} }
func (m *GetFilesRequest) String() string            { return proto.CompactTextString(m) }
func (*GetFilesRequest) ProtoMessage()               {}
func (*GetFilesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetFilesRequest) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

type GetFilesResponse struct {
	Package  string   `protobuf:"bytes,1,opt,name=package" json:"package,omitempty"`
	Filename []string `protobuf:"bytes,2,rep,name=filename" json:"filename,omitempty"`
}

func (m *GetFilesResponse) Reset()                    { *m = GetFilesResponse{} }
func (m *GetFilesResponse) String() string            { return proto.CompactTextString(m) }
func (*GetFilesResponse) ProtoMessage()               {}
func (*GetFilesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetFilesResponse) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *GetFilesResponse) GetFilename() []string {
	if m != nil {
		return m.Filename
	}
	return nil
}

type GetPackagesRequest struct {
	Prefix        string `protobuf:"bytes,1,opt,name=prefix" json:"prefix,omitempty"`
	IncludeVendor bool   `protobuf:"varint,2,opt,name=includeVendor" json:"includeVendor,omitempty"`
}

func (m *GetPackagesRequest) Reset()                    { *m = GetPackagesRequest{} }
func (m *GetPackagesRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPackagesRequest) ProtoMessage()               {}
func (*GetPackagesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetPackagesRequest) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *GetPackagesRequest) GetIncludeVendor() bool {
	if m != nil {
		return m.IncludeVendor
	}
	return false
}

type GetPackagesResponse struct {
	Package []string `protobuf:"bytes,1,rep,name=package" json:"package,omitempty"`
}

func (m *GetPackagesResponse) Reset()                    { *m = GetPackagesResponse{} }
func (m *GetPackagesResponse) String() string            { return proto.CompactTextString(m) }
func (*GetPackagesResponse) ProtoMessage()               {}
func (*GetPackagesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetPackagesResponse) GetPackage() []string {
	if m != nil {
		return m.Package
	}
	return nil
}

func init() {
	proto.RegisterType((*GetFileRequest)(nil), "serve.GetFileRequest")
	proto.RegisterType((*GetFileResponse)(nil), "serve.GetFileResponse")
	proto.RegisterType((*GetAnnotationsRequest)(nil), "serve.GetAnnotationsRequest")
	proto.RegisterType((*GetAnnotationsResponse)(nil), "serve.GetAnnotationsResponse")
	proto.RegisterType((*GetFilesRequest)(nil), "serve.GetFilesRequest")
	proto.RegisterType((*GetFilesResponse)(nil), "serve.GetFilesResponse")
	proto.RegisterType((*GetPackagesRequest)(nil), "serve.GetPackagesRequest")
	proto.RegisterType((*GetPackagesResponse)(nil), "serve.GetPackagesResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Goref service

type GorefClient interface {
	GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error)
	GetAnnotations(ctx context.Context, in *GetAnnotationsRequest, opts ...grpc.CallOption) (*GetAnnotationsResponse, error)
	GetFiles(ctx context.Context, in *GetFilesRequest, opts ...grpc.CallOption) (*GetFilesResponse, error)
	GetPackages(ctx context.Context, in *GetPackagesRequest, opts ...grpc.CallOption) (*GetPackagesResponse, error)
}

type gorefClient struct {
	cc *grpc.ClientConn
}

func NewGorefClient(cc *grpc.ClientConn) GorefClient {
	return &gorefClient{cc}
}

func (c *gorefClient) GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error) {
	out := new(GetFileResponse)
	err := grpc.Invoke(ctx, "/serve.Goref/GetFile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gorefClient) GetAnnotations(ctx context.Context, in *GetAnnotationsRequest, opts ...grpc.CallOption) (*GetAnnotationsResponse, error) {
	out := new(GetAnnotationsResponse)
	err := grpc.Invoke(ctx, "/serve.Goref/GetAnnotations", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gorefClient) GetFiles(ctx context.Context, in *GetFilesRequest, opts ...grpc.CallOption) (*GetFilesResponse, error) {
	out := new(GetFilesResponse)
	err := grpc.Invoke(ctx, "/serve.Goref/GetFiles", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gorefClient) GetPackages(ctx context.Context, in *GetPackagesRequest, opts ...grpc.CallOption) (*GetPackagesResponse, error) {
	out := new(GetPackagesResponse)
	err := grpc.Invoke(ctx, "/serve.Goref/GetPackages", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Goref service

type GorefServer interface {
	GetFile(context.Context, *GetFileRequest) (*GetFileResponse, error)
	GetAnnotations(context.Context, *GetAnnotationsRequest) (*GetAnnotationsResponse, error)
	GetFiles(context.Context, *GetFilesRequest) (*GetFilesResponse, error)
	GetPackages(context.Context, *GetPackagesRequest) (*GetPackagesResponse, error)
}

func RegisterGorefServer(s *grpc.Server, srv GorefServer) {
	s.RegisterService(&_Goref_serviceDesc, srv)
}

func _Goref_GetFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GorefServer).GetFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serve.Goref/GetFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GorefServer).GetFile(ctx, req.(*GetFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Goref_GetAnnotations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnnotationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GorefServer).GetAnnotations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serve.Goref/GetAnnotations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GorefServer).GetAnnotations(ctx, req.(*GetAnnotationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Goref_GetFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GorefServer).GetFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serve.Goref/GetFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GorefServer).GetFiles(ctx, req.(*GetFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Goref_GetPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPackagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GorefServer).GetPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serve.Goref/GetPackages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GorefServer).GetPackages(ctx, req.(*GetPackagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Goref_serviceDesc = grpc.ServiceDesc{
	ServiceName: "serve.Goref",
	HandlerType: (*GorefServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFile",
			Handler:    _Goref_GetFile_Handler,
		},
		{
			MethodName: "GetAnnotations",
			Handler:    _Goref_GetAnnotations_Handler,
		},
		{
			MethodName: "GetFiles",
			Handler:    _Goref_GetFiles_Handler,
		},
		{
			MethodName: "GetPackages",
			Handler:    _Goref_GetPackages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "serve.proto",
}

func init() { proto.RegisterFile("serve.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x92, 0xcf, 0x6e, 0x13, 0x31,
	0x10, 0xc6, 0xd5, 0x84, 0xb6, 0xe9, 0x44, 0x40, 0x35, 0xd0, 0xb0, 0x58, 0x01, 0x82, 0x15, 0x89,
	0xa8, 0x95, 0xd6, 0x50, 0xce, 0x1c, 0x7a, 0x21, 0x1c, 0xd1, 0x1e, 0x38, 0x70, 0x40, 0xb8, 0xe9,
	0xec, 0xd6, 0x6a, 0x6a, 0x2f, 0x5e, 0x27, 0x42, 0x42, 0x5c, 0x78, 0x05, 0x5e, 0x80, 0x77, 0xe2,
	0x15, 0x78, 0x10, 0x14, 0xaf, 0xbb, 0xbb, 0xd9, 0xa6, 0xb9, 0x79, 0xc6, 0x9f, 0xe6, 0x37, 0x7f,
	0x3e, 0xe8, 0x17, 0x64, 0x97, 0x14, 0xe7, 0xd6, 0x38, 0x83, 0xbb, 0x3e, 0x60, 0xc3, 0xcc, 0x98,
	0x6c, 0x4e, 0x42, 0xe6, 0x4a, 0x48, 0xad, 0x8d, 0x93, 0x4e, 0x19, 0x5d, 0x94, 0x22, 0x36, 0xc9,
	0x94, 0xbb, 0x5c, 0x9c, 0xc7, 0x33, 0x73, 0x2d, 0xae, 0x8c, 0x4d, 0x17, 0x56, 0x89, 0xcc, 0x58,
	0x4a, 0x85, 0xff, 0x17, 0x96, 0xd2, 0x52, 0xc9, 0xc7, 0xf0, 0x60, 0x4a, 0xee, 0xbd, 0x9a, 0x53,
	0x42, 0xdf, 0x16, 0x54, 0x38, 0x44, 0xb8, 0x97, 0x4b, 0x77, 0x19, 0xed, 0x8c, 0x76, 0x26, 0x07,
	0x89, 0x7f, 0xf3, 0x33, 0x78, 0x58, 0xa9, 0x8a, 0xdc, 0xe8, 0x82, 0x36, 0xc9, 0x90, 0x41, 0x6f,
	0x66, 0xb4, 0x23, 0xed, 0x8a, 0xa8, 0xe3, 0xf3, 0x55, 0xcc, 0x4f, 0xe0, 0x68, 0x4a, 0xee, 0xac,
	0x6e, 0x75, 0x1b, 0xef, 0x0b, 0x0c, 0xda, 0xe2, 0x2d, 0xd8, 0xd7, 0x00, 0xf5, 0x0a, 0xa2, 0xce,
	0xa8, 0x3b, 0xe9, 0x9f, 0x1e, 0xc6, 0x7e, 0xde, 0x72, 0xca, 0x38, 0xa1, 0x34, 0x69, 0x68, 0xf8,
	0x49, 0x35, 0x4f, 0xd5, 0x46, 0x04, 0xfb, 0xb9, 0x9c, 0x5d, 0xc9, 0x8c, 0x42, 0xed, 0x9b, 0x90,
	0x7f, 0x80, 0xc3, 0x5a, 0x1c, 0xda, 0xb8, 0x53, 0xbd, 0xda, 0x41, 0xaa, 0xe6, 0xa4, 0xe5, 0x35,
	0xf9, 0x56, 0x0e, 0x92, 0x2a, 0xe6, 0x09, 0xe0, 0x94, 0xdc, 0xc7, 0x52, 0x59, 0x91, 0x07, 0xb0,
	0x97, 0x5b, 0x4a, 0xd5, 0xf7, 0x50, 0x2a, 0x44, 0x38, 0x86, 0xfb, 0x4a, 0xcf, 0xe6, 0x8b, 0x0b,
	0xfa, 0x44, 0xfa, 0xc2, 0x58, 0xbf, 0xd2, 0x5e, 0xb2, 0x9e, 0xe4, 0x02, 0x1e, 0xad, 0xd5, 0xdc,
	0xd4, 0x60, 0xb7, 0xd1, 0xe0, 0xe9, 0x9f, 0x2e, 0xec, 0x4e, 0x57, 0xbb, 0xc1, 0xcf, 0xb0, 0x1f,
	0x06, 0xc3, 0xa3, 0xb8, 0xf4, 0xd8, 0xba, 0x17, 0xd8, 0xa0, 0x9d, 0x2e, 0xab, 0xf3, 0xd1, 0xaf,
	0xbf, 0xff, 0x7e, 0x77, 0x18, 0x46, 0x62, 0xf9, 0x26, 0x18, 0x6b, 0x35, 0xa4, 0xf8, 0xb1, 0xba,
	0xc7, 0xbb, 0xe3, 0xe3, 0x9f, 0xb8, 0xf4, 0xbe, 0x6a, 0x5c, 0x10, 0x87, 0x75, 0xad, 0xdb, 0x2e,
	0x60, 0xcf, 0xee, 0xf8, 0x0d, 0xc0, 0x57, 0x1e, 0xf8, 0x12, 0x5f, 0xd4, 0xc0, 0x86, 0xeb, 0x1b,
	0x5c, 0x09, 0xbd, 0x9b, 0x63, 0x61, 0xab, 0xfb, 0x8a, 0xf5, 0xe4, 0x56, 0x3e, 0x50, 0xc6, 0x9e,
	0xf2, 0x1c, 0x87, 0xeb, 0x63, 0xf9, 0xfa, 0x7e, 0x79, 0x1e, 0xf1, 0x15, 0xfa, 0x8d, 0x8d, 0xe3,
	0xd3, 0xba, 0x5a, 0xeb, 0xb2, 0x8c, 0x6d, 0xfa, 0x0a, 0x2c, 0xe6, 0x59, 0x8f, 0x11, 0x6b, 0x56,
	0x80, 0x14, 0xe7, 0x7b, 0xde, 0xb5, 0x6f, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0x3c, 0x4c, 0x51,
	0xee, 0xf9, 0x03, 0x00, 0x00,
}
